import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Blue Bird",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-gray-900 text-gray-100 min-h-screen flex"}>
        {children}
      </body>
    </html>
  );
}
